# Generated by Django 4.2.5 on 2023-10-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('date_founded', models.DateField(verbose_name='Date Founded')),
                ('email', models.EmailField(max_length=254)),
                ('revenue', models.IntegerField()),
            ],
        ),
    ]
